name = "tjuecard-server"
compatibility_date = "2026-01-17"
main = "src/index.ts"

[vars]
# Non-secret environment variables
SEND_CLOUD_FROM_EMAIL = "noreply@tjuecard.ibuhub.com"
SEND_CLOUD_TEST_EMAIL = "hello@ibuhub.com"

# Secrets (use `wrangler secret put <KEY_NAME>`):
# - JWT_SECRET
# - AGENT_SECRET
# - SEND_CLOUD_API_USER
# - SEND_CLOUD_API_KEY

[[d1_databases]]
binding = "DB"
database_name = "tjuecard_app_db"
database_id = "ca92ea53-b0e7-4dc5-a7e3-944e53b7ae42"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1
